/*
 * This file is generated by jOOQ.
 */
package stroom.dashboard.impl.db.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import stroom.dashboard.impl.db.jooq.tables.VisualisationAssetsDraft;


/**
 * A class modelling indexes of tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index VISUALISATION_ASSETS_DRAFT_K_VISUALISATION_ASSETS_DRAFT = Internal.createIndex(DSL.name("k_visualisation_assets_draft"), VisualisationAssetsDraft.VISUALISATION_ASSETS_DRAFT, new OrderField[] { VisualisationAssetsDraft.VISUALISATION_ASSETS_DRAFT.DRAFT_USER_UUID, VisualisationAssetsDraft.VISUALISATION_ASSETS_DRAFT.OWNER_DOC_UUID, VisualisationAssetsDraft.VISUALISATION_ASSETS_DRAFT.PATH_HASH }, false);
}
