/*
 * This file is generated by jOOQ.
 */
package stroom.dashboard.impl.db.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import stroom.dashboard.impl.db.jooq.tables.VisualisationAssets;
import stroom.dashboard.impl.db.jooq.tables.records.VisualisationAssetsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<VisualisationAssetsRecord> KEY_VISUALISATION_ASSETS_K_ASSET_UUID = Internal.createUniqueKey(VisualisationAssets.VISUALISATION_ASSETS, DSL.name("KEY_visualisation_assets_k_asset_uuid"), new TableField[] { VisualisationAssets.VISUALISATION_ASSETS.ASSET_UUID }, true);
    public static final UniqueKey<VisualisationAssetsRecord> KEY_VISUALISATION_ASSETS_PRIMARY = Internal.createUniqueKey(VisualisationAssets.VISUALISATION_ASSETS, DSL.name("KEY_visualisation_assets_PRIMARY"), new TableField[] { VisualisationAssets.VISUALISATION_ASSETS.OWNER_DOC_UUID, VisualisationAssets.VISUALISATION_ASSETS.PATH }, true);
}
