/*
 * This file is generated by jOOQ.
 */
package stroom.dashboard.impl.db.jooq;


import stroom.dashboard.impl.db.jooq.tables.VisualisationAssets;
import stroom.dashboard.impl.db.jooq.tables.VisualisationAssetsDraft;


/**
 * Convenience access to all tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>stroom.visualisation_assets</code>.
     */
    public static final VisualisationAssets VISUALISATION_ASSETS = VisualisationAssets.VISUALISATION_ASSETS;

    /**
     * The table <code>stroom.visualisation_assets_draft</code>.
     */
    public static final VisualisationAssetsDraft VISUALISATION_ASSETS_DRAFT = VisualisationAssetsDraft.VISUALISATION_ASSETS_DRAFT;
}
