/*
 * This file is generated by jOOQ.
 */
package stroom.dashboard.impl.db.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.dashboard.impl.db.jooq.tables.VisualisationAssets;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VisualisationAssetsRecord extends UpdatableRecordImpl<VisualisationAssetsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.visualisation_assets.modified</code>.
     */
    public void setModified(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.visualisation_assets.modified</code>.
     */
    public Long getModified() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.visualisation_assets.owner_doc_uuid</code>.
     */
    public void setOwnerDocUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.visualisation_assets.owner_doc_uuid</code>.
     */
    public String getOwnerDocUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stroom.visualisation_assets.asset_uuid</code>.
     */
    public void setAssetUuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.visualisation_assets.asset_uuid</code>.
     */
    public String getAssetUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stroom.visualisation_assets.path</code>.
     */
    public void setPath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.visualisation_assets.path</code>.
     */
    public String getPath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.visualisation_assets.is_folder</code>.
     */
    public void setIsFolder(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.visualisation_assets.is_folder</code>.
     */
    public Byte getIsFolder() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>stroom.visualisation_assets.data</code>.
     */
    public void setData(byte[] value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.visualisation_assets.data</code>.
     */
    public byte[] getData() {
        return (byte[]) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VisualisationAssetsRecord
     */
    public VisualisationAssetsRecord() {
        super(VisualisationAssets.VISUALISATION_ASSETS);
    }

    /**
     * Create a detached, initialised VisualisationAssetsRecord
     */
    public VisualisationAssetsRecord(Long modified, String ownerDocUuid, String assetUuid, String path, Byte isFolder, byte[] data) {
        super(VisualisationAssets.VISUALISATION_ASSETS);

        setModified(modified);
        setOwnerDocUuid(ownerDocUuid);
        setAssetUuid(assetUuid);
        setPath(path);
        setIsFolder(isFolder);
        setData(data);
        resetChangedOnNotNull();
    }
}
