/*
 * This file is generated by jOOQ.
 */
package stroom.sqlstore.impl.db.jooq.tables.records;


import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.sqlstore.impl.db.jooq.tables.UpdatableTemporalStore;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UpdatableTemporalStoreRecord extends UpdatableRecordImpl<UpdatableTemporalStoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.updatable_temporal_store.map_name</code>.
     */
    public void setMapName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.updatable_temporal_store.map_name</code>.
     */
    public String getMapName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>stroom.updatable_temporal_store.key_</code>.
     */
    public void setKey_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.updatable_temporal_store.key_</code>.
     */
    public String getKey_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stroom.updatable_temporal_store.effective_time</code>.
     */
    public void setEffectiveTime(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.updatable_temporal_store.effective_time</code>.
     */
    public Long getEffectiveTime() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.updatable_temporal_store.value_</code>.
     */
    public void setValue_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.updatable_temporal_store.value_</code>.
     */
    public String getValue_() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, Long> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UpdatableTemporalStoreRecord
     */
    public UpdatableTemporalStoreRecord() {
        super(UpdatableTemporalStore.UPDATABLE_TEMPORAL_STORE);
    }

    /**
     * Create a detached, initialised UpdatableTemporalStoreRecord
     */
    public UpdatableTemporalStoreRecord(String mapName, String key_, Long effectiveTime, String value_) {
        super(UpdatableTemporalStore.UPDATABLE_TEMPORAL_STORE);

        setMapName(mapName);
        setKey_(key_);
        setEffectiveTime(effectiveTime);
        setValue_(value_);
        resetChangedOnNotNull();
    }
}
